import * as terminal from 'control-terminal'

console.log('hello')
terminal.cursor.goTo(10,10)
console.log('world')
terminal.cursor.goTo(9,50)
console.log('haha')
terminal.cursor.goTo(8,8)
console.log('haha')
terminal.cursor.goTo(7,7)
console.log('haha')
terminal.cursor.clearScreen()
console.log('terminal go ->')
terminal.cursor.goTo(40,10)
console.log(terminal.style.bgCyan('Juca Kifuri'))
console.log('has finished haha')