import { AbertoFechado, ContinuoPassoAPasso, LigadoDesligado } from "./memmap-CMPP00LG";
import { Pulses, PulsesPerTick, PulsesPerTickSquared, TicksOfClock } from "./memmap-types";



export type ClassicApi = {
    'Posicao inicial': Pulses,
    'Posicao final': Pulses,
    'Velocidade de avanco': PulsesPerTick,
    'Velocidade de retorno': PulsesPerTick,
    'Aceleracao de avanco': PulsesPerTickSquared,
    'Aceleracao de retorno': PulsesPerTickSquared,
    'Numero de mensagem no avanco': number,
    'Numero de mensagem no retorno': number,
    'Posicao da primeira impressao no avanco': Pulses,
    'Posicao da primeira impressao no retorno': Pulses,
    'Posicao da ultima mensagem no avanco': Pulses,
    'Posicao da ultima mensagem no retorno': Pulses,
    'Largura do sinal de impressao': TicksOfClock,
    'Tempo para o start automatico': TicksOfClock,
    'Tempo para o start externo': TicksOfClock,
    'Retardo para o start automatico passo a passo': TicksOfClock,
    'Start automatico no avanco': LigadoDesligado,
    'Start automatico no retorno': LigadoDesligado,
    'Saida de start no avanco ligado': LigadoDesligado,
    'Saida de start no retorno ligado': LigadoDesligado,
    'Start externo habilitado': LigadoDesligado,
    'Logica do start externo': AbertoFechado,
    'Entrada de start entre eixo habilitado': LigadoDesligado,
    'Start externo para referenciar habilitado': LigadoDesligado,
    'Logica do sinal de impressao': AbertoFechado,
    'Logica do sinal de reversao': AbertoFechado,
    'Selecao de impressao via serial ligada': LigadoDesligado,
    'Reversao de impressao via serial ligada': LigadoDesligado,
    'Zero Index habilitado p/ protecao': LigadoDesligado,
    'Zero Index habilitado p/ correcao': LigadoDesligado,
    'Reducao do nivel de corrente em repouso': LigadoDesligado,
    'Modo continuo/passo a passo': ContinuoPassoAPasso,
    'Retardo para o sinal de impressao': TicksOfClock,
    'Tolerancia de Erro do zero index': Pulses,
    'Numero de pulsos por volta do motor': Pulses,
    'Valor programado da referencia': Pulses,
    'Aceleracao de referencia': PulsesPerTickSquared,
    'Velocidade de referencia': PulsesPerTick,
    'Saida de start passo a passo': LigadoDesligado,
    'Start automatico passo a passo': LigadoDesligado,
    //
    'Start serial': LigadoDesligado,
    'Stop serial': LigadoDesligado,
    'Pausa serial': LigadoDesligado,
    'Modo manual serial': LigadoDesligado,
    'Teste de impressao serial': LigadoDesligado,
}
